'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Namespace DatabaseClient

    Partial Public Class AdventureWorksEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=AdventureWorksEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Products() As DbSet(Of Product)
        Public Overridable Property ProductCategories() As DbSet(Of ProductCategory)
    
        Public Overridable Function GetProductsByColor(color As String) As ObjectResult(Of GetProductsByColor_Result)
            Dim colorParameter As ObjectParameter = If(color IsNot Nothing, New ObjectParameter("color", color), New ObjectParameter("color", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetProductsByColor_Result)("GetProductsByColor", colorParameter)
        End Function
    
    End Class

End Namespace
