'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace DatabaseClient

    Partial Public Class ProductCategory
        Public Property ProductCategoryID As Integer
        Public Property ParentProductCategoryID As Nullable(Of Integer)
        Public Property Name As String
        Public Property rowguid As System.Guid
        Public Property ModifiedDate As Date
    
        Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)
        Public Overridable Property ProductCategory1 As ICollection(Of ProductCategory) = New HashSet(Of ProductCategory)
        Public Overridable Property ProductCategory2 As ProductCategory
    
    End Class

End Namespace
